# Generated by Django 2.0 on 2019-10-30 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=20)),
                ('rated', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=400)),
                ('actors', models.CharField(max_length=500)),
                ('plot', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=300)),
                ('ratings', models.CharField(max_length=500)),
                ('metascore', models.CharField(max_length=50)),
                ('imdbrating', models.CharField(max_length=20)),
                ('imdbvotes', models.CharField(max_length=50)),
                ('imdbid', models.CharField(max_length=50)),
                ('movie_type', models.CharField(max_length=50)),
                ('dvd', models.CharField(max_length=20)),
                ('boxoffice', models.CharField(max_length=50)),
                ('production', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=500)),
                ('response', models.CharField(max_length=10)),
            ],
        ),
    ]
